"""Initial database schema

Revision ID: 6fb68dba4e3f
Revises: 
Create Date: 2026-01-13 03:51:19.237811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fb68dba4e3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.Column('is_venue_owner', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('event_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CORPORATE', 'WEDDING', 'BIRTHDAY', 'ANNIVERSARY', 'NETWORKING', 'CONFERENCE', 'OTHER', name='eventtype'), nullable=False),
    sa.Column('headcount', sa.Integer(), nullable=False),
    sa.Column('date_preferred', sa.Date(), nullable=False),
    sa.Column('date_flexible', sa.Boolean(), nullable=True),
    sa.Column('borough_pref', sa.Enum('MANHATTAN', 'BROOKLYN', 'QUEENS', 'BRONX', 'STATEN_ISLAND', name='borough'), nullable=True),
    sa.Column('neighborhood_pref', sa.String(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=False),
    sa.Column('food_bev_level', sa.Enum('NONE', 'LIGHT_BITES', 'FULL_CATERING', name='foodbevlevel'), nullable=True),
    sa.Column('alcohol_level', sa.Enum('NONE', 'BEER_WINE', 'FULL_BAR', name='alcohollevel'), nullable=True),
    sa.Column('av_needs', sa.Enum('NONE', 'BASIC_MIC', 'FULL_SETUP', name='avneeds'), nullable=True),
    sa.Column('accessibility_needs', sa.Text(), nullable=True),
    sa.Column('vibe', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'MATCHED', 'BOOKED', 'COMPLETED', 'CANCELLED', name='briefstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_briefs_borough_pref'), 'event_briefs', ['borough_pref'], unique=False)
    op.create_index(op.f('ix_event_briefs_created_at'), 'event_briefs', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_briefs_date_preferred'), 'event_briefs', ['date_preferred'], unique=False)
    op.create_index(op.f('ix_event_briefs_event_type'), 'event_briefs', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_briefs_id'), 'event_briefs', ['id'], unique=False)
    op.create_index(op.f('ix_event_briefs_status'), 'event_briefs', ['status'], unique=False)
    op.create_table('message_relay_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_relay_logs_id'), 'message_relay_logs', ['id'], unique=False)
    op.create_index(op.f('ix_message_relay_logs_sent_at'), 'message_relay_logs', ['sent_at'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('borough', sa.Enum('MANHATTAN', 'BROOKLYN', 'QUEENS', 'BRONX', 'STATEN_ISLAND', name='borough'), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('capacity_min', sa.Integer(), nullable=False),
    sa.Column('capacity_max', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('min_spend', sa.Float(), nullable=True),
    sa.Column('instant_book_enabled', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_borough'), 'venues', ['borough'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['event_briefs.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_brief_id'), 'match_results', ['brief_id'], unique=False)
    op.create_index(op.f('ix_match_results_created_at'), 'match_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_match_results_id'), 'match_results', ['id'], unique=False)
    op.create_index(op.f('ix_match_results_venue_id'), 'match_results', ['venue_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('min_spend', sa.Float(), nullable=True),
    sa.Column('included_items', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='offerstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['event_briefs.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_brief_id'), 'offers', ['brief_id'], unique=False)
    op.create_index(op.f('ix_offers_created_at'), 'offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_venue_id'), 'offers', ['venue_id'], unique=False)
    op.create_table('venue_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('amenity_type', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_amenities_id'), 'venue_amenities', ['id'], unique=False)
    op.create_table('venue_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('calendar_url', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id')
    )
    op.create_index(op.f('ix_venue_availability_id'), 'venue_availability', ['id'], unique=False)
    op.create_table('venue_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_hero', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_photos_id'), 'venue_photos', ['id'], unique=False)
    op.create_table('venue_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('min_spend', sa.Float(), nullable=True),
    sa.Column('inclusions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_pricing_id'), 'venue_pricing', ['id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['event_briefs.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_bookings_brief_id'), 'bookings', ['brief_id'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_offer_id'), 'bookings', ['offer_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('reviewee_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_offer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_brief_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_venue_pricing_id'), table_name='venue_pricing')
    op.drop_table('venue_pricing')
    op.drop_index(op.f('ix_venue_photos_id'), table_name='venue_photos')
    op.drop_table('venue_photos')
    op.drop_index(op.f('ix_venue_availability_id'), table_name='venue_availability')
    op.drop_table('venue_availability')
    op.drop_index(op.f('ix_venue_amenities_id'), table_name='venue_amenities')
    op.drop_table('venue_amenities')
    op.drop_index(op.f('ix_offers_venue_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_created_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_brief_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_match_results_venue_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_created_at'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_brief_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_borough'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_message_relay_logs_sent_at'), table_name='message_relay_logs')
    op.drop_index(op.f('ix_message_relay_logs_id'), table_name='message_relay_logs')
    op.drop_table('message_relay_logs')
    op.drop_index(op.f('ix_event_briefs_status'), table_name='event_briefs')
    op.drop_index(op.f('ix_event_briefs_id'), table_name='event_briefs')
    op.drop_index(op.f('ix_event_briefs_event_type'), table_name='event_briefs')
    op.drop_index(op.f('ix_event_briefs_date_preferred'), table_name='event_briefs')
    op.drop_index(op.f('ix_event_briefs_created_at'), table_name='event_briefs')
    op.drop_index(op.f('ix_event_briefs_borough_pref'), table_name='event_briefs')
    op.drop_table('event_briefs')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
